version: '3'
services:
  db:
    build: faucet-db
    hostname: vet-faucet-db
    ports:
      - "27017:27017"
    volumes:
      - "faucet_db:/data/db"
      - "faucet_configdb:/data/configdb"
  web:
    build: .
    hostname: vet-faucet-web
    ports:
      - "8000:8000"
    volumes:
      - "./configs:/opt/vet-faucet/configs:ro"
    depends_on:
      - db
    links:
      - db
volumes:
  faucet_db:
  faucet_configdb:
